<?php

/*
 * Tabela de referencia do fornecedor, 04/2026, transcrita dos PDFs de temp/.
 *
 * ARQUIVO GERADO por tools/gera_precos_catalogo.py. Nao edite a mao: rode o
 * script de novo quando o fornecedor publicar tabela nova.
 *
 * Precos em centavos, na ordem das faixas. Sao preco de VENDA ao cliente da
 * Avalia; o custo do fornecedor e cadastrado separadamente e nao vem daqui.
 */

return [
    // Consumo minimo de cada faixa, em centavos. A primeira e "sem minimo".
    'faixas' => [0, 7_500, 20_000, 50_000, 90_000, 150_000, 500_000],

    'servicos' => [
        [
            'codigo' => 'cheques-sem-fundos',
            'nome' => 'Cheques sem fundos — Banco Central PF/PJ',
            'categoria' => 'credito',
            'exige_liberacao' => false,
            'precos' => [209, 188, 170, 153, 137, 124, 98],
        ],
        [
            'codigo' => 'acoes-judiciais',
            'nome' => 'Ações judiciais — nacional PF/PJ',
            'categoria' => 'credito',
            'exige_liberacao' => false,
            'precos' => [594, 522, 460, 405, 356, 313, 234],
        ],
        [
            'codigo' => 'scpc-bvs',
            'nome' => 'SCPC BVS PF/PJ — Base III',
            'categoria' => 'credito',
            'exige_liberacao' => false,
            'precos' => [631, 594, 558, 524, 493, 463, 370],
        ],
        [
            'codigo' => 'relatorio-plus',
            'nome' => 'Relatório Plus PF/PJ + cartórios e CCF Bacen — Base III',
            'categoria' => 'credito',
            'exige_liberacao' => false,
            'precos' => [781, 742, 705, 670, 636, 604, 540],
        ],
        [
            'codigo' => 'credito-net-basica',
            'nome' => 'Crédito Net Básica PF/PJ — Base I',
            'categoria' => 'credito',
            'exige_liberacao' => false,
            'precos' => [1_593, 1_513, 1_437, 1_366, 1_297, 1_232, 1_097],
        ],
        [
            'codigo' => 'mix',
            'nome' => 'Mix PF/PJ — Base I e II',
            'categoria' => 'credito',
            'exige_liberacao' => false,
            'precos' => [1_852, 1_741, 1_637, 1_539, 1_446, 1_360, 1_201],
        ],
        [
            'codigo' => 'credito-net',
            'nome' => 'Crédito Net PF/PJ — Base I e III',
            'categoria' => 'credito',
            'exige_liberacao' => false,
            'precos' => [1_897, 1_783, 1_676, 1_575, 1_481, 1_392, 1_226],
        ],
        [
            'codigo' => 'credito-net-top',
            'nome' => 'Crédito Net Top + cartórios e CCF Bacen — Base I e III',
            'categoria' => 'credito',
            'exige_liberacao' => false,
            'precos' => [2_191, 2_059, 1_936, 1_820, 1_710, 1_608, 1_421],
        ],
        [
            'codigo' => 'score-positivo',
            'nome' => 'Relatório Score Positivo + filtros — Base III',
            'categoria' => 'credito',
            'exige_liberacao' => false,
            'precos' => [993, 944, 897, 852, 809, 769, 694],
        ],
        [
            'codigo' => 'risco-credito-top',
            'nome' => 'Risco de Crédito Top PF/PJ + filtros — Base I',
            'categoria' => 'credito',
            'exige_liberacao' => false,
            'precos' => [2_095, 1_969, 1_851, 1_740, 1_636, 1_538, 1_359],
        ],
        [
            'codigo' => 'relatorio-top',
            'nome' => 'Relatório Top PF/PJ + filtros — Base I e III',
            'categoria' => 'credito',
            'exige_liberacao' => false,
            'precos' => [2_857, 2_743, 2_633, 2_528, 2_427, 2_330, 2_125],
        ],
        [
            'codigo' => 'relatorio-top-scr',
            'nome' => 'Relatório Top + SCR — Base I e III',
            'categoria' => 'credito',
            'exige_liberacao' => true,
            'precos' => [4_450, 4_094, 3_767, 3_465, 3_188, 2_933, 2_699],
        ],
        [
            'codigo' => 'maxi-top',
            'nome' => 'Maxi Top PF/PJ + score e filtros — Base I e II',
            'categoria' => 'credito',
            'exige_liberacao' => false,
            'precos' => [2_815, 2_703, 2_595, 2_491, 2_391, 2_296, 2_094],
        ],
        [
            'codigo' => 'prime-basica',
            'nome' => 'Relatório Prime Básica + cartórios e CCF Bacen — Base I, II e III',
            'categoria' => 'credito',
            'exige_liberacao' => false,
            'precos' => [2_670, 2_510, 2_359, 2_218, 2_085, 1_960, 1_709],
        ],
        [
            'codigo' => 'prime-completa',
            'nome' => 'Relatório Prime Completa + filtros — Base I, II e III',
            'categoria' => 'credito',
            'exige_liberacao' => false,
            'precos' => [3_705, 3_520, 3_344, 3_177, 3_018, 2_867, 2_560],
        ],
        [
            'codigo' => 'prime-completa-scr',
            'nome' => 'Relatório Prime Completa + SCR — Base I, II e III',
            'categoria' => 'credito',
            'exige_liberacao' => true,
            'precos' => [5_289, 4_866, 4_477, 4_118, 3_789, 3_486, 3_242],
        ],
        [
            'codigo' => 'scr-score',
            'nome' => 'SCR + score PF/PJ',
            'categoria' => 'credito',
            'exige_liberacao' => true,
            'precos' => [2_003, 1_883, 1_770, 1_664, 1_564, 1_470, 1_299],
        ],
        [
            'codigo' => 'cadastro-especial-pf',
            'nome' => 'Cadastro especial PF — endereço, telefone, e-mail, trabalho, renda',
            'categoria' => 'credito',
            'exige_liberacao' => false,
            'precos' => [303, 273, 246, 221, 199, 179, 145],
        ],
        [
            'codigo' => 'cadastro-especial-pj',
            'nome' => 'Cadastro especial PJ — dados da empresa, sócios, regime fiscal, faturamento',
            'categoria' => 'credito',
            'exige_liberacao' => false,
            'precos' => [303, 273, 246, 221, 199, 179, 145],
        ],
        [
            'codigo' => 'telefones-por-documento',
            'nome' => 'Telefones por CPF/CNPJ',
            'categoria' => 'credito',
            'exige_liberacao' => false,
            'precos' => [111, 100, 90, 81, 73, 66, 53],
        ],
        [
            'codigo' => 'enderecos-por-documento',
            'nome' => 'Endereços por CPF/CNPJ',
            'categoria' => 'credito',
            'exige_liberacao' => false,
            'precos' => [111, 100, 90, 81, 73, 66, 53],
        ],
        [
            'codigo' => 'infobusca-por-documento',
            'nome' => 'InfoBusca por CPF/CNPJ — telefone, endereço e e-mails',
            'categoria' => 'credito',
            'exige_liberacao' => false,
            'precos' => [207, 186, 167, 151, 136, 122, 99],
        ],
        [
            'codigo' => 'infobusca-por-nome',
            'nome' => 'InfoBusca por nome (mostra CPF)',
            'categoria' => 'credito',
            'exige_liberacao' => false,
            'precos' => [207, 186, 167, 151, 136, 122, 99],
        ],
        [
            'codigo' => 'localizador-por-telefone',
            'nome' => 'Localizador por telefone (mostra nome e CPF/CNPJ)',
            'categoria' => 'credito',
            'exige_liberacao' => false,
            'precos' => [207, 186, 167, 151, 136, 122, 99],
        ],
        [
            'codigo' => 'localizador-por-cep',
            'nome' => 'Localizador por CEP (mostra nomes e CPF/CNPJ)',
            'categoria' => 'credito',
            'exige_liberacao' => false,
            'precos' => [207, 186, 167, 151, 136, 122, 99],
        ],
        [
            'codigo' => 'negativacao',
            'nome' => 'Negativação',
            'categoria' => 'credito',
            'exige_liberacao' => false,
            'precos' => [1_790, 1_790, 1_790, 1_790, 1_790, 1_790, 1_790],
        ],
        [
            'codigo' => 'localiza-veiculos',
            'nome' => 'Localiza veículos por CPF/CNPJ',
            'categoria' => 'veicular',
            'exige_liberacao' => false,
            'precos' => [2_156, 2_048, 1_946, 1_849, 1_756, 1_668, 1_426],
        ],
        [
            'codigo' => 'historico-proprietario-sp',
            'nome' => 'Histórico de proprietário (somente São Paulo)',
            'categoria' => 'veicular',
            'exige_liberacao' => false,
            'precos' => [1_430, 1_387, 1_345, 1_305, 1_266, 1_228, 1_155],
        ],
        [
            'codigo' => 'proprietario-atual',
            'nome' => 'Proprietário atual',
            'categoria' => 'veicular',
            'exige_liberacao' => false,
            'precos' => [594, 576, 559, 542, 526, 510, 480],
        ],
        [
            'codigo' => 'agregados',
            'nome' => 'Agregados',
            'categoria' => 'veicular',
            'exige_liberacao' => false,
            'precos' => [363, 352, 342, 331, 321, 312, 293],
        ],
        [
            'codigo' => 'renajud',
            'nome' => 'RenaJud',
            'categoria' => 'veicular',
            'exige_liberacao' => false,
            'precos' => [1_055, 1_013, 973, 934, 896, 861, 793],
        ],
        [
            'codigo' => 'renainf',
            'nome' => 'RenaInf — infrações completa',
            'categoria' => 'veicular',
            'exige_liberacao' => false,
            'precos' => [897, 861, 827, 794, 762, 731, 674],
        ],
        [
            'codigo' => 'crlv',
            'nome' => 'CRLV — documento de licenciamento',
            'categoria' => 'veicular',
            'exige_liberacao' => false,
            'precos' => [2_378, 2_307, 2_237, 2_170, 2_105, 2_042, 1_921],
        ],
        [
            'codigo' => 'bin',
            'nome' => 'BIN — base estadual e nacional',
            'categoria' => 'veicular',
            'exige_liberacao' => false,
            'precos' => [596, 572, 549, 527, 506, 486, 448],
        ],
        [
            'codigo' => 'leilao',
            'nome' => 'Leilão — Base I',
            'categoria' => 'veicular',
            'exige_liberacao' => false,
            'precos' => [1_194, 1_158, 1_123, 1_089, 1_057, 1_025, 954],
        ],
        [
            'codigo' => 'leilao-conjugado',
            'nome' => 'Leilão conjugado completo + score do veículo — Base II',
            'categoria' => 'veicular',
            'exige_liberacao' => false,
            'precos' => [2_195, 2_129, 2_065, 2_003, 1_943, 1_884, 1_755],
        ],
        [
            'codigo' => 'csv-veicular',
            'nome' => 'CSV — certificado de segurança veicular',
            'categoria' => 'veicular',
            'exige_liberacao' => false,
            'precos' => [795, 771, 748, 725, 703, 682, 635],
        ],
        [
            'codigo' => 'roubo-e-furto',
            'nome' => 'Histórico de roubo e furto',
            'categoria' => 'veicular',
            'exige_liberacao' => false,
            'precos' => [799, 767, 737, 707, 679, 652, 594],
        ],
        [
            'codigo' => 'gravame',
            'nome' => 'Gravame indicativo',
            'categoria' => 'veicular',
            'exige_liberacao' => false,
            'precos' => [795, 763, 732, 703, 675, 648, 597],
        ],
        [
            'codigo' => 'gravame-agregados',
            'nome' => 'Gravame indicativo + agregados',
            'categoria' => 'veicular',
            'exige_liberacao' => false,
            'precos' => [1_100, 1_056, 1_014, 973, 934, 897, 827],
        ],
        [
            'codigo' => 'confere-rg-cnh',
            'nome' => 'Confere RG/CNH',
            'categoria' => 'veicular',
            'exige_liberacao' => false,
            'precos' => [588, 570, 553, 537, 521, 505, 475],
        ],
        [
            'codigo' => 'precificador',
            'nome' => 'Precificador / decodificador',
            'categoria' => 'veicular',
            'exige_liberacao' => false,
            'precos' => [595, 577, 560, 543, 527, 511, 481],
        ],
        [
            'codigo' => 'vip-car',
            'nome' => 'VIP Car — informação completa do veículo',
            'categoria' => 'veicular',
            'exige_liberacao' => false,
            'precos' => [5_530, 5_364, 5_203, 5_047, 4_896, 4_749, 4_468],
        ],
    ],
];
